id: A9D489E59
title: Prayer to Jamyang Khyentse Chökyi Lodrö
type: translation
pechas:
- I1CD40DFB
- I2F059419
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:48:52.955784
  last_modified_at: 2023-01-04 11:48:52.955798
  collections:
  - Dudjom Rinpoche Series
  - Works of Tibetan Masters
alignment_to_base:
  I1CD40DFB/9464: 855C
  I2F059419/37A2: 855C
